# Generated by Django 6.0.3 on 2026-09-25 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CASH_OUT', 'Cash Out'), ('TRANSFER', 'Transfer'), ('PAYMENT', 'Payment'), ('DEBIT', 'Debit'), ('CASH_IN', 'Cash In')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sender_id', models.CharField(max_length=50)),
                ('sender_old_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('sender_new_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('receiver_id', models.CharField(max_length=50)),
                ('receiver_old_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('receiver_new_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('niveau', models.CharField(choices=[('Faible', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Eleve'), ('CRITIQUE', 'Critique')], max_length=10)),
                ('explication', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='detection.transaction')),
            ],
        ),
    ]
